# Intermediate Neural Network in Tensorflow
Build a intermadiate neural network to classify handwritten digits


## Load correct version of TensorFlow

In [0]:
# Install TensorFlow using Colab's tensorflow_version command
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

TensorFlow 2.x selected.


# Load Dependencies here

In [0]:
import tensorflow 
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from matplotlib import pyplot as plt


# Load Data

In [0]:
(X_train, y_train), (X_valid, y_valid) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


# Preprocess data

In [0]:
X_train = X_train.reshape(60000,784).astype('float32')
X_valid = X_valid.reshape(10000,784).astype('float32')

In [0]:
X_train /= 255
X_valid /= 255

In [0]:
X_valid[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [0]:
n_classes = 10
y_train = to_categorical(y_train, n_classes)
y_valid = to_categorical(y_valid, n_classes)

Design NN arch

In [0]:
model = Sequential()

# hidden layer:
model.add(Dense(64, activation='relu', input_shape=(784,)))
model.add(Dense(64, activation='relu'))

#output layer:
model.add(Dense(10, activation='softmax'))

In [0]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                50240     
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 55,050
Trainable params: 55,050
Non-trainable params: 0
_________________________________________________________________


## Compile model

In [0]:
model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.1), metrics=['accuracy'])

# Train model

In [0]:
model.fit(X_train,y_train, batch_size=128, epochs=20, verbose=1, validation_data=(X_valid, y_valid))

Train on 60000 samples, validate on 10000 samples
Epoch 1/20
60000/60000 [==============================] - 1s 24us/sample - loss: 0.0099 - accuracy: 0.9984 - val_loss: 0.0993 - val_accuracy: 0.9753
Epoch 2/20
60000/60000 [==============================] - 1s 25us/sample - loss: 0.0091 - accuracy: 0.9986 - val_loss: 0.0954 - val_accuracy: 0.9762
Epoch 3/20
60000/60000 [==============================] - 2s 25us/sample - loss: 0.0082 - accuracy: 0.9990 - val_loss: 0.0958 - val_accuracy: 0.9777
Epoch 4/20
60000/60000 [==============================] - 2s 27us/sample - loss: 0.0076 - accuracy: 0.9991 - val_loss: 0.0966 - val_accuracy: 0.9765
Epoch 5/20
60000/60000 [==============================] - 2s 25us/sample - loss: 0.0070 - accuracy: 0.9993 - val_loss: 0.0993 - val_accuracy: 0.9764
Epoch 6/20
60000/60000 [==============================] - 2s 25us/sample - loss: 0.0065 - accuracy: 0.9992 - val_loss: 0.0985 - val_accuracy: 0.9762
Epoch 7/20
60000/60000 [==============================] 

## Evaluating model performance

In [0]:
model.evaluate(X_valid, y_valid)

10000/10000 [==============================] - 0s 42us/sample - loss: 0.1090 - accuracy: 0.9763


[0.10898282212174036, 0.9763]

Performing inference

In [0]:
valid_0 = X_valid[0]. reshape(1, 784)
model.predict(valid_0)

array([[5.2986641e-13, 7.9118972e-10, 5.1850044e-08, 8.4961887e-04,
        1.3331820e-12, 7.0210000e-08, 2.0212827e-21, 9.9914956e-01,
        7.2487488e-08, 6.7546989e-07]], dtype=float32)

In [0]:
model.predict_classes(valid_0)

array([7])