# Regression Example in Tensorflow
Predicting house prices in Boston, Massachusetts

# Load correct version of TensorFlow

In [0]:
# Install TensorFlow using Colab's tensorflow_version command
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

# Load dependencies

In [0]:
import numpy as np
from tensorflow.keras.datasets import boston_housing # new
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint # new
import os # new

Load data

In [0]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

In [0]:
X_train.shape

(404, 13)

In [0]:
X_valid.shape

(102, 13)

In [0]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [0]:
y_train[0]

15.2

# Design neural network architecture

In [0]:
model = Sequential()

# First hidden layer:
model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

# Second hidden layer:
model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

# Output layer:
model.add(Dense(1, activation='linear'))

In [0]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 32)                448       
_________________________________________________________________
batch_normalization_3 (Batch (None, 32)                128       
_________________________________________________________________
dense_7 (Dense)              (None, 16)                528       
_________________________________________________________________
batch_normalization_4 (Batch (None, 16)                64        
_________________________________________________________________
dropout_1 (Dropout)          (None, 16)                0         
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 17        
Total params: 1,185
Trainable params: 1,089
Non-trainable params: 96
___________________________________________________

# Configure Model

In [0]:
model.compile(loss='mean_squared_error', optimizer='nadam', )

In [0]:
output_dir = 'model_output/'

In [0]:
run_name = 'regression_baseline'
output_path = output_dir + run_name

In [0]:
if not os.path.exists(output_path):
  os.makedirs(output_path)

In [0]:
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.hdf5', # decimal integers
                                  save_weights_only=True) 

Train!

In [0]:
model.fit(X_train, y_train, 
          batch_size=8, epochs=32, verbose=1, 
          validation_data=(X_valid, y_valid),
          callbacks=[modelcheckpoint]) # val loss below 50 is good, 40 great

Train on 404 samples, validate on 102 samples
Epoch 1/32
404/404 [==============================] - 0s 376us/sample - loss: 560.0601 - val_loss: 603.2470
Epoch 2/32
404/404 [==============================] - 0s 384us/sample - loss: 542.4919 - val_loss: 594.8527
Epoch 3/32
404/404 [==============================] - 0s 338us/sample - loss: 524.5152 - val_loss: 547.4297
Epoch 4/32
404/404 [==============================] - 0s 406us/sample - loss: 499.9703 - val_loss: 523.5482
Epoch 5/32
404/404 [==============================] - 0s 360us/sample - loss: 478.7455 - val_loss: 508.6233
Epoch 6/32
404/404 [==============================] - 0s 363us/sample - loss: 445.6235 - val_loss: 484.2178
Epoch 7/32
404/404 [==============================] - 0s 327us/sample - loss: 412.6755 - val_loss: 502.7804
Epoch 8/32
404/404 [==============================] - 0s 329us/sample - loss: 369.9393 - val_loss: 448.7210
Epoch 9/32
404/404 [==============================] - 0s 376us/sample - loss: 333.1423 - v

# Performing inference




In [0]:
model.load_weights(output_path + '/weights.20.hdf5')

In [0]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [0]:
y_valid[42]

14.1

In [0]:
model.predict(np.reshape(X_valid[42], [1, 13]))

array([[9.892089]], dtype=float32)