# Regression Example in TensorFlow
Predicting house prices in Boston, Massachusetts 

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/jonkrohn/DLTFpT/blob/master/notebooks/regression_in_tensorflow.ipynb)

#### Load dependencies

In [0]:
import numpy as np
from tensorflow.keras.datasets import boston_housing # new!
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout 
from tensorflow.keras.layers import BatchNormalization 
from tensorflow.keras.callbacks import ModelCheckpoint # new!
import os # new!

#### Load data

In [0]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

In [0]:
X_train.shape

(404, 13)

In [0]:
X_valid.shape

(102, 13)

In [0]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [0]:
y_train[0]

15.2

#### Design neural network architecture

In [0]:
model = Sequential()

model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(1, activation='linear'))

In [0]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                448       
_________________________________________________________________
batch_normalization (BatchNo (None, 32)                128       
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
_________________________________________________________________
batch_normalization_1 (Batch (None, 16)                64        
_________________________________________________________________
dropout (Dropout)            (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 17        
Total params: 1,185
Trainable params: 1,089
Non-trainable params: 96
_____________________________________________________

#### Configure Model

In [0]:
model.compile(loss='mean_squared_error', optimizer='adam', )

In [0]:
output_dir = 'model_output/'

In [0]:
run_name = 'regression_baseline'
output_path = output_dir + run_name

In [0]:
if not os.path.exists(output_path):
    os.makedirs(output_path)

In [0]:
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.hdf5', # decimal integers
                                  save_weights_only=True) 

#### Train!

In [0]:
model.fit(X_train, y_train, 
          batch_size=8, epochs=32, verbose=1, 
          validation_data=(X_valid, y_valid),
          callbacks=[modelcheckpoint]) # val loss below 50 is good, 40 great

Train on 404 samples, validate on 102 samples
Epoch 1/32
404/404 [==============================] - 1s 1ms/sample - loss: 574.9674 - val_loss: 670.9787
Epoch 2/32
404/404 [==============================] - 0s 283us/sample - loss: 560.1075 - val_loss: 610.3649
Epoch 3/32
404/404 [==============================] - 0s 272us/sample - loss: 538.9081 - val_loss: 569.0831
Epoch 4/32
404/404 [==============================] - 0s 292us/sample - loss: 523.4382 - val_loss: 532.6724
Epoch 5/32
404/404 [==============================] - 0s 346us/sample - loss: 498.2580 - val_loss: 513.4582
Epoch 6/32
404/404 [==============================] - 0s 382us/sample - loss: 473.1501 - val_loss: 482.6169
Epoch 7/32
404/404 [==============================] - 0s 349us/sample - loss: 444.2933 - val_loss: 448.3360
Epoch 8/32
404/404 [==============================] - 0s 316us/sample - loss: 408.2028 - val_loss: 410.1629
Epoch 9/32
404/404 [==============================] - 0s 311us/sample - loss: 374.2431 - val

#### Performing inference

In [0]:
model.load_weights(output_path + '/weights.20.hdf5')

In [0]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [0]:
y_valid[42]

14.1

In [0]:
model.predict(np.reshape(X_valid[42], [1, 13]))

array([[15.265093]], dtype=float32)